FROM mcr.microsoft.com/dotnet/core/aspnet:5.0 AS base
WORKDIR /source

COPY *.sln .
COPY ConsoleApp1/*.csproj ./ConsoleApp1/
RUN dotnet restore

COPY ConsoleApp1/. ./ConsoleApp1/
WORKDIR /source/ConsoleApp1
RUN dotnet publish -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "ConsoleApp1.dll"]
